name: Running mapproxy lint

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read  #  to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Use python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: flake8 Lint
        uses: py-actions/flake8@v2
